# **Convolution Neural Network (CNN)**

In [2]:
import numpy as np


def convolution_layer(
    input_matrix: np.array, filter_matrix: np.array, stride: int, padding: str = "valid"
) -> np.array:
    """
    Convolutional layer
    :param input_matrix: 2D numpy array
    :param filter_matrix: 2D numpy array
    :param stride: int
    :param padding: str
    :return: 2D numpy array
    """
    # Get the dimensions of the input matrix and the filter matrix
    input_rows, input_cols = input_matrix.shape
    filter_rows, filter_cols = filter_matrix.shape

    # Check if the padding is valid
    if padding == "valid":
        # Calculate the output dimensions
        output_rows = (input_rows - filter_rows) // stride + 1
        output_cols = (input_cols - filter_cols) // stride + 1

        # Initialize the output matrix
        output_matrix = np.zeros((output_rows, output_cols))

        # Iterate over the input matrix
        for i in range(0, output_rows):
            for j in range(0, output_cols):
                output_matrix[i, j] = np.sum(
                    input_matrix[
                        i * stride : i * stride + filter_rows,
                        j * stride : j * stride + filter_cols,
                    ]
                    * filter_matrix
                )

    elif padding == "same":
        # Calculate the output dimensions
        output_rows = input_rows
        output_cols = input_cols

        # Calculate the padding
        pad_rows = int(
            np.ceil(((output_rows - 1) * stride + filter_rows - input_rows) / 2)
        )
        pad_cols = int(
            np.ceil(((output_cols - 1) * stride + filter_cols - input_cols) / 2)
        )

        # Pad the input matrix
        input_matrix = np.pad(
            input_matrix, ((pad_rows, pad_rows), (pad_cols, pad_cols)), mode="constant"
        )

        # Initialize the output matrix
        output_matrix = np.zeros((output_rows, output_cols))

        # Iterate over the input matrix
        for i in range(0, output_rows):
            for j in range(0, output_cols):
                output_matrix[i, j] = np.sum(
                    input_matrix[
                        i * stride : i * stride + filter_rows,
                        j * stride : j * stride + filter_cols,
                    ]
                    * filter_matrix
                )

    return output_matrix

In [3]:
# test
input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
filter_matrix = np.array([[1, 0], [0, 1]])

print(convolution_layer(input_matrix, filter_matrix, 2, "valid"))

[[ 7. 11.]
 [23. 27.]]


In [4]:
# Input
input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
filter_matrix = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])

print(convolution_layer(input_matrix, filter_matrix, 1, "valid"))

[[30. 35.]
 [50. 55.]]


In [5]:
# Use padding
input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
filter_matrix = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])

print(convolution_layer(input_matrix, filter_matrix, 1, "same"))

[[ 7. 14. 17. 11.]
 [17. 30. 35. 22.]
 [15. 22. 25. 19.]]


In [6]:
# Use padding
input_matrix = np.array(
    [
        [1, 2, 0, 1, 3],
        [4, 1, 0, 2, 1],
        [0, 3, 1, 0, 2],
        [2, 1, 0, 3, 1],
        [1, 2, 4, 0, 3],
    ]
)
filter_matrix = np.array([[1, 0, -1], [0, 1, 0], [-1, 0, 1]])

print(convolution_layer(input_matrix, filter_matrix, 1, "valid"))

[[ 3. -2.  0.]
 [ 5.  2.  0.]
 [ 3.  1.  1.]]


In [7]:
def pooling_layer(
    input_matrix: np.array,
    pool_size: int,
    stride: int,
    padding: str = "valid",
    mode="average",
) -> np.array:
    """
    Pooling layer
    :param input_matrix: 2D numpy array
    :param pool_size: int
    :param stride: int
    :param padding: str
    :param mode: str
    :return: 2D numpy array
    """
    # Get the dimensions of the input matrix
    input_rows, input_cols = input_matrix.shape

    # Check if the padding is valid
    if padding == "valid":
        # Calculate the output dimensions
        output_rows = (input_rows - pool_size) // stride + 1
        output_cols = (input_cols - pool_size) // stride + 1

        # Initialize the output matrix
        output_matrix = np.zeros((output_rows, output_cols))

        # Iterate over the input matrix
        for i in range(0, output_rows):
            for j in range(0, output_cols):
                if mode == "max":
                    output_matrix[i, j] = np.max(
                        input_matrix[
                            i * stride : i * stride + pool_size,
                            j * stride : j * stride + pool_size,
                        ]
                    )
                elif mode == "average":
                    output_matrix[i, j] = np.mean(
                        input_matrix[
                            i * stride : i * stride + pool_size,
                            j * stride : j * stride + pool_size,
                        ]
                    )

    elif padding == "same":
        # Calculate the output dimensions
        output_rows = input_rows
        output_cols = input_cols

        # Calculate the padding
        pad_rows = int(
            np.ceil(((output_rows - 1) * stride + pool_size - input_rows) / 2)
        )
        pad_cols = int(
            np.ceil(((output_cols - 1) * stride + pool_size - input_cols) / 2)
        )

        # Pad the input matrix
        input_matrix = np.pad(
            input_matrix, ((pad_rows, pad_rows), (pad_cols, pad_cols)), mode="constant"
        )

        # Initialize the output matrix
        output_matrix = np.zeros((output_rows, output_cols))

        # Iterate over the input matrix
        for i in range(0, output_rows):
            for j in range(0, output_cols):
                if mode == "max":
                    output_matrix[i, j] = np.max(
                        input_matrix[
                            i * stride : i * stride + pool_size,
                            j * stride : j * stride + pool_size,
                        ]
                    )
                elif mode == "average":
                    output_matrix[i, j] = np.mean(
                        input_matrix[
                            i * stride : i * stride + pool_size,
                            j * stride : j * stride + pool_size,
                        ]
                    )

    return output_matrix

In [8]:
# test
input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(pooling_layer(input_matrix, 2, 1, "same", "max"))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [9]:
print(pooling_layer(input_matrix, 2, 1, "valid", "average"))

[[3.5 4.5 5.5]
 [7.5 8.5 9.5]]


HW: Re-implement the CNN function in this notebook.